// Example of server component file (e.g., `app/layout.tsx`)
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Skill on Time',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
